### ISSUE TITLE
Unable to pay to non-latin Lightning address

### ISSUE THREAD

**Issue by Liongrass** [ACINQ/phoenix#307] opened 2022-10-25 05:07 UTC
Paying to a latin Lightning address works as expected, e.g. `leo@bitcoin.org.hk`.

I'm trying to pay to a non-latin Lightning address (`leo@比特幣.組織.香港`). Phoenix notices my Lightning address in my clip board and offers to "Paste from clipboard" where the LN address is correctly shown. 

I click on "Pay from clipboard"

I get the error "Could not connect to service: 比特幣.組織.香港"

**Comment by robbiehanson** [comment] 2022-10-25 08:13
Duplicate of #264

**Closed by robbiehanson** 2022-10-25 08:13 UTC
