### ISSUE TITLE
Funds received on-chain don't swap automatically 

### ISSUE THREAD

**Issue by nick1981** [ACINQ/phoenix#582] opened 2024-07-06 15:06 UTC
Hi Team,

Please check my issue here 🔗 [https://x.com/pio_taras/status/1809601751143665940?t=y0glAc9hlFBDcAz0gjQjJQ&s=19]()

Thanks.

**Comment by t-bast** [comment] 2024-07-08 13:57
This is fixed by https://github.com/ACINQ/lightning-kmp/pull/681: this was indeed a bug caused by an edge case in the migration from the legacy app, because you had a tiny utxo (701 sat) that wasn't economical to swap and incorrectly blocked the next swaps. This will be fixed in the next release and your pending swap will automatically complete after the app update.

**Closed** 2024-07-08 15:06 UTC
