### ISSUE TITLE
Cannot pay LNURL pay with Phoenix IOS

### ISSUE THREAD

**Issue by johnongit** [ACINQ/phoenix#217] opened 2021-10-30 14:21 UTC
it seems Phoenix iOS cannot pay an LNURL pay created by  lnbits web app.
Phoenix Android (and other wallet) can pay it.

We can reproduce the bug with the following LNURL p.
https://lnbits.openchain.fr/lnurlp/44

Phoenix returns "Invalid response"

![image](https://user-images.githubusercontent.com/16493486/139536773-1a959a9e-1da4-4388-9e56-3d86f9f5bb4a.png)

**Comment by robbiehanson** [comment] 2021-11-09 20:30
Confirmed bug. Response from lnbits is:
```json
{"pr":"lnbc1...","routes":[],"successAction":null}
```

Crash occurs because code expects `successAction` to be a JsonObject, and not JsonNull. Fix incoming...

**Comment by robbiehanson** [comment] 2021-11-24 14:04
Thanks for reporting this bug. It should be fixed in the next release: v1.2.1

**Closed by robbiehanson** 2021-11-24 14:04 UTC
