### ISSUE TITLE
Allow phoenix: uri prefix in in-app qr scanner

### ISSUE THREAD

**Issue by davidknezic** [ACINQ/phoenix#368] opened 2023-06-22 09:50 UTC
It's great to see the existence of the `phoenix:` uri prefix for deep-linking into Phoenix specifically:

* https://github.com/ACINQ/phoenix/blob/b8a0562bc6e1a13491f494bae3187cae0ee63a1e/phoenix-android/src/main/kotlin/fr/acinq/phoenix/android/AppView.kt#L98-L99
* https://github.com/ACINQ/phoenix/blob/b8a0562bc6e1a13491f494bae3187cae0ee63a1e/phoenix-ios/phoenix-ios/SceneDelegate.swift#L165-L166

I noticed that when using the in-app scanner, the `phoenix:` uri prefix breaks reading an invoice or LNURL:

| phoenix:lightning:LNURL... | [lightning:]LNURL... |
|---|---|
| <img src="https://github.com/ACINQ/phoenix/assets/198988/ef3c44ea-d456-4a0d-a9ae-635a6ce5a829" alt="phoenix" /> | <img src="https://github.com/ACINQ/phoenix/assets/198988/003f80a5-5525-4ae0-bb16-034c9dfa620f" alt="phoenix" /> |

Would you accept a contribution to add support for the `phoenix:` and `phoenix://` prefixes to the in-app scanner, too?

This would make the behaviour consistent no matter if scanned with a system qr scanner or inside of Phoenix itself.

**Comment by dpad85** [comment] 2023-06-22 11:12
Hello David, thanks for reporting this issue. I was actually testing that this morning, and noticed that the scanner would not trim the `phoenix` scheme from the scanned data. I already made a fix which should be available in the next version (though that version will not be released soon, as it contains many significant changes, see #356).

In any case I don't think the QR code should contain the `phoenix:lightning:` scheme, or any scheme in fact. It should only contain the relevant payload, in your case the LNURL data. The scheme makes the QR code heavier (making in marginally harder to read) and is ignored anyway. 

That being said, Phoenix should be smart and be able to read that kind of QR codes, so the fix is still needed.

**Comment by dpad85** [comment] 2023-06-22 11:17
Just to be sure, I tried scanning a QR-code containing the `phoenix:lightning:` scheme directly from the OS camera app, wondering if it would redirect to Phoenix (like it would with a `phoenix:lightning:` hyperlink):
- on Android, the camera app does not understand it's an URI and does not redirect to Phoenix
- on iOS, the camera app does redirect to Phoenix

So having the scheme in the QR code could still be useful in some cases.

**Comment by dpad85** [comment] 2023-09-08 14:55
Closing this ticket as the issue is fixed, re-open it if not, thanks!

**Closed by dpad85** 2023-09-08 14:55 UTC
